lib/timesheets_web/router.ex
defmodule TimesheetsWeb.Router do
  use TimesheetsWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(TimesheetsWeb.Plugs.FetchCurrentUser)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :ajax do
    plug(:accepts, ["json"])
    plug(:fetch_session)
    plug(TimesheetsWeb.Plugs.FetchCurrentUser)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  scope "/", TimesheetsWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
    resources("/users", UserController)
    resources("/requests", RequestController)
    resources("/tasks", TaskController)
    resources("/sessions", SessionController, only: [:new, :create, :delete], singleton: true)
  end

  scope "/ajax", TimesheetsWeb do
    pipe_through(:ajax)
  end
end

lib/timesheets/requests.ex
defmodule Timesheets.Requests do
  @moduledoc """
  The Requests context.
  """

  import Ecto.Query, warn: false
  alias Timesheets.Repo

  alias Timesheets.Requests.Request

  @doc """
  Returns the list of requests.

  ## Examples

      iex> list_requests()
      [%Request{}, ...]

  """
  def list_requests do
    Repo.all(Request)
  end

  @doc """
  Gets a single request.

  Raises `Ecto.NoResultsError` if the Request does not exist.

  ## Examples

      iex> get_request!(123)
      %Request{}

      iex> get_request!(456)
      ** (Ecto.NoResultsError)

  """
  def get_request!(id), do: Repo.get!(Request, id)

  @doc """
  Creates a request.

  ## Examples

      iex> create_request(%{field: value})
      {:ok, %Request{}}

      iex> create_request(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_request(attrs \\ %{}) do
    %Request{}
    |> Request.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a request.

  ## Examples

      iex> update_request(request, %{field: new_value})
      {:ok, %Request{}}

      iex> update_request(request, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_request(%Request{} = request, attrs) do
    request
    |> Request.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Request.

  ## Examples

      iex> delete_request(request)
      {:ok, %Request{}}

      iex> delete_request(request)
      {:error, %Ecto.Changeset{}}

  """
  def delete_request(%Request{} = request) do
    Repo.delete(request)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking request changes.

  ## Examples

      iex> change_request(request)
      %Ecto.Changeset{source: %Request{}}

  """
  def change_request(%Request{} = request) do
    Request.changeset(request, %{})
  end
end

lib/timesheets/requests/request.ex
defmodule Timesheets.Requests.Request do
  use Ecto.Schema
  import Ecto.Changeset

  schema "requests" do
    field :approval, :boolean, default: false
    field :date, :date
    field :user_id, :id
    field :manager_id, :id
    

    timestamps()
  end

  @doc false
  def changeset(request, attrs) do
    request
    |> cast(attrs, [:approval, :date, :user_id, :manager_id])
    |> validate_required([:approval, :date, :user_id, :manager_id])
  end


end

lib/timesheets_web/controllers/request_controller.ex
defmodule TimesheetsWeb.RequestController do
  use TimesheetsWeb, :controller

  alias Timesheets.Requests
  alias Timesheets.Requests.Request
  alias Timesheets.Tasks

  def index(conn, _params) do
    requests = Requests.list_requests()
    render(conn, "index.html", requests: requests)
  end

  def new(conn, _params) do
    changeset = Requests.change_request(%Request{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"request" => request_params}) do
    case Requests.create_request(request_params) do
      {:ok, request} ->
        conn
        |> put_flash(:info, "Request created successfully.")
        |> redirect(to: Routes.request_path(conn, :show, request))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    IO.puts("In show")
    request = Requests.get_request!(id)
    changeset = Requests.change_request(request)
    tasks = Tasks.list_tasks_by_request_id(id)
    IO.puts("tasks")
    IO.inspect(tasks)
    render(conn, "show.html", request: request, tasks: tasks, changeset: changeset)
  end

  def edit(conn, %{"id" => id}) do
    request = Requests.get_request!(id)
    IO.puts("in edit")
    IO.inspect(request)
    request = Map.put(request, :approval, true)
    changeset = Requests.change_request(request)
    case Requests.update_request(request) do
      {:ok, _} ->
        IO.puts("step ahead")
        conn
        |> put_flash(:info, "Request approved successfully.")
        |> redirect(to: Routes.request_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        IO.puts("Some error occured")
        render(conn, "show.html", request: request, changeset: changeset)
    end

    # changeset = Requests.change_request(request)
    # render(conn, "edit.html", request: request, changeset: changeset)
  end

  def update(conn, %{"id" => id, "request" => attrs}) do
    IO.puts("hti")
    request = Requests.get_request!(id)
    # request = Map.put(request, :approval, req.approval)
    IO.inspect(request)
    IO.puts("out here")
    case Requests.update_request(request, attrs) do
      {:ok, request} ->
        conn
        |> put_flash(:info, "Request updated successfully.")
        |> redirect(to: Routes.request_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        IO.puts("Some error occured")
        render(conn, "show.html", request: request, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    request = Requests.get_request!(id)
    {:ok, _request} = Requests.delete_request(request)

    conn
    |> put_flash(:info, "Request deleted successfully.")
    |> redirect(to: Routes.request_path(conn, :index))
  end
end

lib/timesheets_web/views/request_view.ex
defmodule TimesheetsWeb.RequestView do
  use TimesheetsWeb, :view
end

lib/timesheets_web/templates/request/edit.html.eex
<h1>Edit Request</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.request_path(@conn, :update, @request)) %>

<span><%= link "Back", to: Routes.request_path(@conn, :index) %></span>

lib/timesheets_web/templates/request/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
  <div class="form-group">
  <%= label f, :date %>
  <%= date_select f, :date %>
  <%= error_tag f, :date %>
</div>

  <div class="form-group">
     <%= hidden_input f, :user_id, value: @current_user.id, class: "form-control" %>
     <%= error_tag f, :user_id %>
   </div>


<div class="form-group">
   <%= hidden_input f, :manager_id, value: @current_user.manager_id, class: "form-control" %>
   <%= error_tag f, :manager_id %>
 </div>


  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/timesheets_web/templates/request/index.html.eex
<h1>Listing Requests</h1>

<%= if @current_user.role == "worker" do %>
  <span><%= link "New Request", to: Routes.request_path(@conn, :new) %></span>
    <div class="col-md-12">
      <div class="row">
      <div class="col-md-4 col-sm-4">
        <span>Approval Status</span>
      </div>
      <div class="col-md-4 col-sm-4">
        <span>Date</span>
      </div>

    </div>
    </div>

<%= for request <- @requests do %>

      <div class="col-md-12">
        <div class="row">
        <div class="col-md-4 col-sm-4"
      <%= if request.approval === true do %>
    <span>Approved</span>
      <% else %>
        <span>Not Yet Approved
      </span>

      <% end %>
</div>


<div class="col-md-4 col-sm-4">

      <span><%= request.date %></span>
    </div>

    </div>
    <div class="col-md-4 col-sm-4">

      <span><%= link "View Request", to: Routes.request_path(@conn, :show, request.id) %></span>
      </span>
        </div>

        </div>


  </div>
<% end %>
<% else %>
<div class = "col-md-12">
  <div class="col-md-12">
    <div class="row">
    <div class="col-md-4 col-sm-4">
      <span>Approve</span>
    </div>
    <div class="col-md-4 col-sm-4">
      <span>Date</span>
    </div>
  </div>
  </div>

  <%= for request <- @requests do %>
  <%= if request.approval === false && request.manager_id == @current_user.id do %>
    <div class="col-md-12">
      <div class="row">
      <div class="col-md-4 col-sm-4"

        <span>
        <%= link "View Request", to: Routes.request_path(@conn, :show, request.id) %></span>

  </div>

  <div class="col-md-4 col-sm-4">

    <span><%= request.date %></span>
  </div>
  </div>
  </div>
  <% end %>
<% end %>
<% end %>

lib/timesheets_web/templates/request/new.html.eex
<h1>New Request</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.request_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.request_path(@conn, :index) %></span>

lib/timesheets_web/templates/request/show.html.eex
<h1>Show Request</h1>

<ul>

  <li>
    <strong>Approval:</strong>
    <%= @request.approval %>
  </li>

  <li>
    <strong>Date:</strong>
    <%= @request.date %>
  </li>

</ul>

<span><%= link "View tasks", to: Routes.task_path(@conn, :index, request_id: @request.id) %></span>



<%= if @current_user && @current_user.role == "manager" do %>
<!-- <span><%= link "Approve", to:
Routes.request_path(@conn, :edit, @request) %></span> -->


<%= form_for @changeset, Routes.request_path(@conn, :update, @request), fn f ->%>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
     <%= hidden_input f, :approval, value: true, class: "form-control" %>
   </div>


  <div>
    <%= submit "Approve" %>
  </div>
<% end %>


<% end %>


<span><%= link "Back", to: Routes.request_path(@conn, :index) %></span>